kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-consumer-application
  labels:
    app_name:  kafka-consumer-application
spec:
  revisionHistoryLimit: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 10
  replicas: 1
  selector:
    matchLabels:
      app_name:  kafka-consumer-application
  template:
    metadata:
      labels:
        app_name:  kafka-consumer-application
    spec:
      containers:
        - name:  kafka-application
          image:  confluentinc/cp-kafka:5.0.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              while true
                do
                kafka-console-consumer --bootstrap-server scraper-kafka-bootstrap:9092 --topic my-topic --from-beginning --group we-consume --timeout-ms 2000 --max-messages 1
                sleep 30
              done
