apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: scraper
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      message.max.bytes: 4194304
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.retention.ms: 60000
      log.message.format.version: "2.4"
      connections.max.idle.ms: 2400000
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 500Gi
        deleteClaim: true
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 120
      timeoutSeconds: 60
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 120
      timeoutSeconds: 60
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
